# Interface callback flags. Enable for each implemented method
#
# _HF_MANGLERESIZECALLBACK: 
#   Input file resize routine (for dynamic size mangling)
#
# _HF_MANGLECALLBACK:
#   Main content mangling routine
#
# _HF_POSTMANGLECALLBACK:
#   Post mangling routine

EXTENSION_CFLAGS  := -D_HF_POSTMANGLECALLBACK
EXTENSION_LDFLAGS := 
